### ISSUE TITLE
可以添加点击事件吗？

### ISSUE THREAD

**Issue by dingxiansen1** [liangjingkanji/Tooltip#5]
我尝试在这个位置添加点击事件(类似番茄小说进入首页的提示，上次阅读XXX,单机继续阅读的效果)
  // 等级Toast
            onLevel { context, msg, level ->
                when (level) {
                    TOAST_ERROR -> {
                        view = View.inflate(context, R.layout.layout_toast_error, null)
                            .apply {
                                tv_msg.text = msg
                                tv_msg.setOnClickListener {
                                     Log.e("单机","单机")
                               }
                            }
                    }
                }
            }
发现并没有生效,，是设置的方式有问题吗？

**Comment by liangjingkanji** [comment]
你说的效果是用SnackBar实现的, 而Toast在Android最新系统中被禁止自定义了

**Comment by dingxiansen1** [comment]
哦，好的，多谢指教
