### ISSUE TITLE
Toast 在 Android 7.1 崩溃的问题

### ISSUE THREAD

**Issue by syxc** [liangjingkanji/Tooltip#7]
Toast 在 Android 7.1 崩溃的问题，这个可否兼容一下？

**Comment by liangjingkanji** [comment]
使用官方Api不存在崩溃, 也许应该参考 Duplicate of #6

**Comment by syxc** [comment]
> 使用官方Api不存在崩溃, 也许应该参考 Duplicate of #6

好的
